---
kind: Secret
apiVersion: v1
metadata:
  name: git-secrets
stringData:
  AUTH_GITHUB_APP_ID: REPLACE_WITH_YOUR_GITHUB_APP_ID
  AUTH_GITHUB_CLIENT_ID: REPLACE_WITH_YOUR_GITHUB_CLIENT_ID
  AUTH_GITHUB_CLIENT_SECRET: REPLACE_WITH_YOUR_GITHUB_CLIENT_SECRET
  AUTH_GITHUB_WEBHOOK_URL: REPLACE_WITH_YOUR_GITHUB_WEBHOOK_URL
  AUTH_GITHUB_WEBHOOK_SECRET: REPLACE_WITH_YOUR_GITHUB_WEBHOOK_SECRET
  AUTH_GITHUB_PRIVATE_KEY_FILE: |
    REPLACE_WITH_YOUR_GITHUB_PRIVATE_KEY_FILE
  GITHUB_ORGANIZATION: REPLACE_WITH_YOUR_GITHUB_ORGANIZATION
type: Opaque
