---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-app-config
data:
  rhdh-app-config.yaml: |
    backend:
      baseUrl: https://$rhdhname.$basedomain
      cors:
        origin: https://$rhdhname.$basedomain
    organization:
      name: "My Organization"
    app:
      baseUrl: https://$rhdhname.$basedomain
      title: "My Adventure with Red Hat Developer Hub"
      branding:
        theme:
          light:
            primaryColor: '#38be8b'
            headerColor1: 'hsl(204 100% 71%)'
            headerColor2: 'color(a98-rgb 1 0 0)'
            navigationIndicatorColor: '#be0000'
          dark:
            primaryColor: '#ab75cf'
            headerColor1: '#0000d0'
            headerColor2: 'rgb(255 246 140)'
            navigationIndicatorColor: '#f4eea9'

    # Authorization GitLab
    signInPage: gitlab
    auth:
      environment: development
      providers:
        gitlab:
          development:
            clientId: ${AUTH_GITLAB_CLIENT_ID}
            clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
            audience: https://gitlab.${basedomain}
            signIn:
              resolvers:
                - resolver: usernameMatchingUserEntityName
                  dangerouslyAllowSignInWithoutUserInCatalog: true
