global:
  clusterRouterBase: "${basedomain}"
  dynamic:
    includes:
      - dynamic-plugins.default.yaml
    plugins:
      # GitLab Plugins
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-catalog-backend-module-gitlab-org-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/backstage-plugin-scaffolder-backend-module-gitlab-dynamic
        disabled: false
      # GitLab Plugins
      - package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab-backend-dynamic
        disabled: false
      - package: ./dynamic-plugins/dist/immobiliarelabs-backstage-plugin-gitlab
        disabled: false
      # RBAC Plugins
      - package: ./dynamic-plugins/dist/backstage-community-plugin-rbac
        disabled: false
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: rhdh-app-config
        filename: rhdh-app-config.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets
      - git-secrets
    extraVolumeMounts:
      - mountPath: /opt/app-root/src/dynamic-plugins-root
        name: dynamic-plugins-root
      - mountPath: /opt/app-root/src/rbac
        name: rbac-policies
    extraVolumes:
      - name: dynamic-plugins-root
        persistentVolumeClaim:
          claimName: 'rhdh-dynamic-plugins-root'
      - configMap:
          defaultMode: 420
          name: 'rhdh-dynamic-plugins'
          optional: true
        name: dynamic-plugins
      - name: dynamic-plugins-npmrc
        secret:
          defaultMode: 420
          optional: true
          secretName: 'rhdh-dynamic-plugins-npmrc'
      - name: dynamic-plugins-registry-auth
        secret:
          defaultMode: 416
          optional: true
          secretName: 'rhdh-dynamic-plugins-registry-auth'
      - name: npmcacache
      - configMap:
          defaultMode: 420
          name: rbac-policies
        name: rbac-policies
