---
apiVersion: v1
kind: Namespace
metadata:
  name: rhdh-operator
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  annotations:
    olm.providedAPIs: Backstage.v1alpha1.rhdh.redhat.com
  name: rhdh-operator-og
  namespace: rhdh-operator
spec:
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  labels:
    operators.coreos.com/rhdh.rhdh-operator: ""
  name: rhdh
  namespace: rhdh-operator
spec:
  name: rhdh
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  channel: fast
  startingCSV: rhdh-operator.v1.4.0
  installPlanApproval: Automatic
