---
# Default GitHub labels
- color: d73a4a
  name: bug
  description: Something isn't working
- color: cfd3d7
  name: duplicate
  description: This issue or pull request already exists
- color: a2eeef
  name: enhancement
  description: New feature or request
- color: 7057ff
  name: good first issue
  description: Good for newcomers
- color: 008672
  name: help wanted
  description: Extra attention is needed
- color: e4e669
  name: invalid
  description: This doesn't seem right
- color: d876e3
  name: question
  description: Further information is requested
- color: ffffff
  name: wontfix
  description: This will not be worked on

# Label templates
- name: "📄 documentation"
  description: Documenting something
  color: "#0075ca"

- name: "🚀 enhancement"
  description: New enhancement or request
  color: "#a2eeef"

- name: "✨ feature"
  description: New feature or request
  color: "#DA40D7"

- name: "🐞 bug"
  description: Something isn't working
  color: "#d73a4a"

- name: "🐛 Fix"
  description: Fixing something
  color: "#6B8557"

- name: "⚠️ changed"
  description: Changing something
  color: "#FEE006"

- name: "⛔️ deprecated"
  description: Deprecating something
  color: "#7A038D"

- name: "🗑 removed"
  description: Removing something
  color: "#7584A3"

- name: "🔐 security"
  description: Securing something
  color: "#C7F25D"

- name: "🧩 dependencies"
  description: Dependency Updates
  color: "#1FBB8E"

- name: "⚙️ stale"
  description: Stale
  color: "#E01A80"

- name: "🗑️ duplicate"
  color: cfd3d7
  description: This issue or pull request already exists
