apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: rhdh-adventure
  description: |
    This is an adventure to introduce your teams in features and capabilities of Red Hat Developer Hub improving Developer Experience and Developer Productivity.
  links:
    - title: Website
      url: https://rhdh-adventure-organization.github.io/rhdh-adventure/rhdh-adventure/index.html
  annotations:
    github.com/project-slug: 'rhdh-adventure-organization/rhdh-adventure'
    backstage.io/kubernetes-id: rhdh-adventure
    backstage.io/techdocs-ref: dir:.
spec:
  type: website
  lifecycle: production
  owner: rhdh
