= Setup
include::_attributes.adoc[]

[#intro]
== 🧾 Streamline Future App Dev

You have an application skeleton; or scaffold or archetype; for a kind of architecture very common in your organization. However, it is a manual process using it to create new applications.

Here you will create a software template using your application skeleton to onboard new applications in Red Hat Developer Hub. This onboarding process will include the creation of the source code repository, and the default dashboard of the application into the catalog with integrations with the documentation, dependencies (if applies) and API (if applies).

[#softwaretemplate]
== 💀 Software Template

Create your own software template or use one already created and register in Red Hat Developer Hub to be used
by the developers to create new applications.

To resolve this challenge you can start checking the following references:

* link:https://redhatquickcourses.github.io/devhub-intro/devhub-intro/1/features/gpt.html[Introduction to Software Templates]
* link:https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html[A deeper dive into Software Templates]
* link:https://github.com/redhat-developer/red-hat-developer-hub-software-templates[Red Hat Developer Hub Software Templates Library]

[#softwaretemplate-solution]
=== 🧞💀 Software Template Solution

Are you struggling about how to resolve it? Don't worry you can check the solution xref:challenge-05-solution.adoc#softwaretemplate-solution[here].

[#onboard]
== 🛬 Onboarding

Just use the software template declared previously and create a new application using it. The process must
finish successfully with a new component registered into the Red Hat Developer Hub catalog.

To resolve this challenge you can start checking the following references:

* link:https://redhatquickcourses.github.io/devhub-intro/devhub-intro/1/features/gpt.html[Introduction to Software Templates]
* link:https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html[A deeper dive into Software Templates]
* link:https://github.com/redhat-developer/red-hat-developer-hub-software-templates[Red Hat Developer Hub Software Templates Library]

[#onboard-solution]
=== 🧞🛬 Onboarding Solution

Are you struggling about how to resolve it? Don't worry you can check the solution xref:challenge-05-solution.adoc#onboard-solution[here].
