[#intro]
= 🧾 Streamline Future App Dev
include::_attributes.adoc[]
:page-toclevels: 1

Your team has a valuable **application skeleton**, scaffold, or archetype that aligns with a common architecture
in your organization. However, manually replicating this skeleton for every new application slows you down and
introduces inefficiencies. This challenge is about turning that manual process into a **streamlined, automated workflow**
using Red Hat Developer Hub **software templates**.

In this stage, you will:

* Create a **software template** based on your existing application skeleton, or
* Use a **software template** from the community, and
* Onboard new applications seamlessly by automating the creation of a **source code repository** and setting up
a **default dashboard** in the catalog, complete with documentation, dependencies (if applicable),
and API integrations (if applicable).

The stage is complete when:

* Your software template is successfully registered in the catalog.
* A new application or component is created using the template, onboarded into the catalog, and includes
all required resources (source code repository, documentation, dependencies, APIs).

With this challenge, you'll move beyond manual processes and embrace the power of automation.
Empower your team to onboard new applications quickly and consistently, reducing friction and ensuring every
project starts with the right foundation.

[#softwaretemplate]
== 💀 Software Template

Create your own software template or use one already created and register in Red Hat Developer Hub to be used
by the developers to create new applications.

To resolve this challenge you can start checking the following references:

* link:https://redhatquickcourses.github.io/devhub-intro/devhub-intro/1/features/gpt.html[Introduction to Software Templates]
* link:https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html[A deeper dive into Software Templates]
* link:https://github.com/redhat-developer/red-hat-developer-hub-software-templates[Red Hat Developer Hub Software Templates Library]
* link:https://developers.redhat.com/learn/streamline-development-github-integration-and-software-templates-red-hat-developer-hub[Streamline Development: GitHub Integration and Software Templates in Red Hat Developer Hub]
* link:https://docs.redhat.com/en/documentation/red_hat_developer_hub/1.8/html-single/customizing_red_hat_developer_hub/index#proc-enabling-software-template-version-update-notifications_configuring-templates[Enabling Software Template version update notifications in Red Hat Developer Hub]

[#softwaretemplate-solution]
=== 🧞💀 Software Template Solution

Are you struggling about how to resolve it? Don't worry you can check the solution xref:challenge-05-solution.adoc#softwaretemplate-solution[here].

[#onboard]
== 🛬 Onboarding

Just use the software template declared previously and create a new application using it. The process must
finish successfully with a new component registered into the Red Hat Developer Hub catalog.

To resolve this challenge you can start checking the following references:

* link:https://redhatquickcourses.github.io/devhub-intro/devhub-intro/1/features/gpt.html[Introduction to Software Templates]
* link:https://redhatquickcourses.github.io/devhub-build/devhub-build/1/chapter1/templates.html[A deeper dive into Software Templates]
* link:https://github.com/redhat-developer/red-hat-developer-hub-software-templates[Red Hat Developer Hub Software Templates Library]

[#onboard-solution]
=== 🧞🛬 Onboarding Solution

Are you struggling about how to resolve it? Don't worry you can check the solution xref:challenge-05-solution.adoc#onboard-solution[here].
