---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-app-config
data:
  rhdh-app-config.yaml: |
    backend:
      baseUrl: https://$rhdhname.$basedomain
      cors:
        origin: https://$rhdhname.$basedomain
    organization:
      name: "My Organization"
    app:
      baseUrl: https://$rhdhname.$basedomain
      title: "My Adventure with Red Hat Developer Hub"
      branding:
        theme:
          light:
            primaryColor: '#38be8b'
            headerColor1: 'hsl(204 100% 71%)'
            headerColor2: 'color(a98-rgb 1 0 0)'
            navigationIndicatorColor: '#be0000'
          dark:
            primaryColor: '#ab75cf'
            headerColor1: '#0000d0'
            headerColor2: 'rgb(255 246 140)'
            navigationIndicatorColor: '#f4eea9'

    # Authorization GitLab
    signInPage: gitlab
    dangerouslyAllowSignInWithoutUserInCatalog: true
    auth:
      environment: production
      providers:
        gitlab:
          production:
            clientId: ${AUTH_GITLAB_CLIENT_ID}
            clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
            audience: https://gitlab.${basedomain}

    # Integrations
    integrations:
      gitlab:
        - host: gitlab.${basedomain}
          token: ${AUTH_GITLAB_TOKEN}
          apiBaseUrl: https://gitlab.${basedomain}/api/v4
          baseUrl: https://gitlab.${basedomain}

    # Catalog
    catalog:
      providers:
        gitlab:
          myGitLab:
            host: gitlab.${basedomain} # Identifies one of the hosts set up in the integrations
            apiBaseUrl: https://gitlab.${basedomain}/api/v4
            branch: main # Optional. Used to discover on a specific branch
            fallbackBranch: master # Optional. Fallback to be used if there is no default branch configured at the Gitlab repository. It is only used, if `branch` is undefined. Uses `master` as default
            skipForkedRepos: false # Optional. If the project is a fork, skip repository
            entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
            projectPattern: '[\s\S]*' # Optional. Filters found projects based on provided patter. Defaults to `[\s\S]*`, which means to not filter anything
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }
            orgEnabled: true
            #group: org/teams # Required for gitlab.com when `orgEnabled: true`. Optional for self managed. Must not end with slash. Accepts only groups under the provided path (which will be stripped)
            allowInherited: true # Allow groups to be ingested even if there are no direct members.
            groupPattern: '[\s\S]*'
            restrictUsersToGroup: false

      # Locations
      locations:
        - type: url
          target: https://github.com/redhat-developer/red-hat-developer-hub-software-templates/blob/main/templates.yaml
          rules:
            - allow: [Template]

    # RBAC
    permission:
      enabled: true
      rbac:
        admin:
          users:
            #- name: user:default/adminID
            - name: user:default/rmarting
        policies-csv-file: /opt/app-root/src/rbac/rbac-policies.csv
        policyFileReload: true
        pluginsWithPermission:
          - catalog
          - scaffolder
          - permission
