apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-root
  namespace: openshift-gitops
spec:
  project: rhdh-adventure
  source:
    repoURL: 'https://github.com/rmarting/rhdh-adventure.git'
    targetRevision: master
    path: "argocd/apps"
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-adventure
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
