apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rhdh-config
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/rmarting/rhdh-adventure.git'
    targetRevision: main
    path: "argocd/rhdh-config"
  destination:
    server: https://kubernetes.default.svc
    namespace: rhdh-adventure
  syncPolicy:
    automated: {}
