global:
  # -- Shorthand for users who do not want to specify a custom HOSTNAME. Used ONLY with the DEFAULT upstream.backstage.appConfig value and with OCP Route enabled.
  clusterRouterBase: "apps-crc.testing"
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: rhdh-app-config
        filename: rhdh-app-config.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets
