---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-app-config
data:
  rhdh-app-config.yaml: |
    organization:
      name: "My Organization"
    app:
      title: "My Adventure with Red Hat Developer Hub"
