---
kind: ConfigMap
apiVersion: v1
metadata:
  name: rhdh-app-config
data:
  rhdh-app-config.yaml: |
    backend:
      baseUrl: https://$rhdhname.$basedomain
      cors:
        origin: https://$rhdhname.$basedomain
    organization:
      name: "My Organization"
    app:
      baseUrl: https://$rhdhname.$basedomain
      title: "My Adventure with Red Hat Developer Hub"
