global:
  clusterRouterBase: "${basedomain}"
  #dynamic:
  #  plugins: []
upstream:
  backstage:
    extraAppConfig:
      - configMapRef: rhdh-app-config
        filename: rhdh-app-config.yaml
    extraEnvVarsSecrets:
      - rhdh-secrets
