name: 🌐 Build and publish GitHub pages site

on:
  push:
    branches:
      - master
    paths-ignore:
      - 'README.adoc'
      - 'CHANGELOG.md'
      - 'CONTRIBUTING.md'
      - 'CONTRIBUTORS.adoc'
      - 'CODE_OF_CONDUCT.md'

permissions:
  contents: write

env:
  SITE_DIR: "gh-pages"

jobs:
  build_site:
    name: "Build site with Antora"
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: "Generate site using antora site action"
        uses: kameshsampath/antora-site-action@master
        with:
          antora_playbook: site.yml
      - name: "Upload generated site"
        uses: actions/upload-artifact@v4.0.0
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
  deploy_site:
    runs-on: [ubuntu-latest]
    needs: [build_site]
    name: "Deploy GitHub Pages"
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Download generated site
        uses: actions/download-artifact@v4
        with:
          name: site
          path: "${{ github.workspace }}/${{ env.SITE_DIR }}"
      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4.7.3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FOLDER: "${{ env.SITE_DIR }}"
          BRANCH: "gh-pages"
          COMMIT_MESSAGE: "🚀 Publish Documentation for ${{ github.sha }}"
