name: 👷 Check Content

on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.adoc'

permissions:
  pull-requests: read

jobs:
  check-links:
    name: Check broken links
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Documentation
        uses: actions/checkout@v4.2.2

      - name: Run linkspector
        uses: umbrelladocs/action-linkspector@v1.3.4
        with:
          github_token: ${{ secrets.github_token }}
          config_file: .github/linters/linkspector.yml
          reporter: github-pr-review
          fail_level: any
          show_stats: true