name: 📄 Update Contributors and Changelog

on:
  workflow_run:
    workflows:
      - "🔖 Release Publisher"
    types:
      - "completed"

jobs:
  update:
    name: Update Contributors and Changelog
    runs-on: ubuntu-latest
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # updated CHANGELOG back to the repository.
      # https://github.blog/changelog/2023-02-02-github-actions-updating-the-default-github_token-permissions-to-read-only/
      contents: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - id: checkout-code
        name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: master
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: update-contributors
        name: Contribute List
        uses: akhilmhdh/contributors-readme-action@v2.3.10
        with:
          readme_path: CONTRIBUTORS.md
          commit_message: 👥 Update contributors family
          pr_title_on_protected: 👥 Update contributors family
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - id: get-latest-release
        name: Get Latest Release
        uses: pozetroninc/github-action-get-latest-release@v0.8.0
        with:
          repository: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - id: update-changelog
        name: Update Changelog
        uses: stefanzweifel/changelog-updater-action@v1.12.0
        with:
          latest-version: ${{ steps.get-latest-release.outputs.release }}
          release-notes: ${{ steps.get-latest-release.outputs.description }}

      - id: commit-update-changelog
        name: Commit updated Changelog
        uses: stefanzweifel/git-auto-commit-action@v5.1.0
        with:
          branch: master
          commit_message: '🔖 Update changelog'
          file_pattern: CHANGELOG.md
          push_options: --force
